name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to droplet via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            echo "== Start at $(date) =="

            cd /root

            if [ ! -d "CNS_Bot" ]; then
              echo "== Cloning repo at $(date) =="
              git clone https://github.com/ENIGMA-RL/CNS_Bot.git
            fi

            cd CNS_Bot

            echo "== Pulling latest changes at $(date) =="
            git pull origin main

            echo "== Installing dependencies at $(date) =="
            npm install
            echo "== Dependencies installed at $(date) =="

            echo "== Writing .env at $(date) =="
            cat > .env <<EOL
DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}
DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }}
DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
GUILD_ID=${{ secrets.GUILD_ID }}
LOG_CHANNEL_ID=${{ secrets.LOG_CHANNEL_ID }}
OAUTH_PORT=${{ secrets.OAUTH_PORT }}
WELCOME_CHANNEL_ID=${{ secrets.WELCOME_CHANNEL_ID }}
EOL

            echo "== Restarting bot via PM2 at $(date) =="
            pm2 restart CNSBot || pm2 start src/index.js --name CNSBot
            pm2 save

            echo "== Finished at $(date) ==" 