name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to droplet via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            echo "== Start at $(date) =="

            cd /root

            if [ ! -d "4RCU5_BOT" ]; then
              echo "== Cloning repo at $(date) =="
              git clone https://github.com/ENIGMA-RL/4RCU5_BOT.git
            fi

            cd 4RCU5_BOT

            echo "== Pulling latest changes at $(date) =="
            git pull origin main

            if git diff --name-only HEAD@{1} HEAD | grep -E 'package(-lock)?\\.json'; then
              echo "[+] Detected dependency changes. Running npm install..."
              npm install
            else
              echo "[✓] No dependency changes. Skipping npm install."
            fi
            echo "== Dependencies step complete at $(date) =="

            echo "== Writing .env at $(date) =="
            echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" > .env
            echo "DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }}" >> .env
            echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
            echo "GUILD_ID=${{ secrets.GUILD_ID }}" >> .env
            echo "LOG_CHANNEL_ID=${{ secrets.LOG_CHANNEL_ID }}" >> .env
            echo "OAUTH_PORT=${{ secrets.OAUTH_PORT }}" >> .env
            echo "WELCOME_CHANNEL_ID=${{ secrets.WELCOME_CHANNEL_ID }}" >> .env
            echo "SKIP_GIVEAWAYS_MIGRATION=${{ secrets.SKIP_GIVEAWAYS_MIGRATION }}" >> .env

            echo "== Restarting bot via PM2 at $(date) =="
            pm2 stop CNSBot || true
            pm2 delete CNSBot || true
            pm2 start src/index.js --name CNSBot
            pm2 save

            echo "== Finished at $(date) ==" 